version: '3.8'

services:
  geth:
    image: ethereum/client-go:v1.14.13
    container_name: geth-node
    command:
      - --syncmode=full
      - --state.scheme=hash
      - --networkid=7014190335
      - --verbosity=3
      - --datadir=/data/geth/execution-data
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=admin,engine,net,eth,web3,debug
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,engine,net,eth,web3,debug
      - --ws.origins=*
      - --authrpc.port=8551
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/jwt/jwtsecret
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=6060
      - --port=30303
      - --bootnodes=enode://c15b5973b8fc6e5152d1d442512e5024b25883f2e002564cfa29cc3b748d687756c9f674f021f142eeea5711697a3d43d2bc36f13b1e20fe11b341676921430e@18.192.40.76:30303?discport=30303,enode://35cd13c4d555d70b39aafa806f817c4707397f7f9b7a1d43237f73d279c318fda0e4ba8a4b10d1f8b7771992804209aa028f74bd846afc86d016c4728a1c5268@35.156.177.215:30303?discport=30303,enode://dba7a24e543cc924178ed7e0066e5e40caa17607474a25b50e4bea7b565dee9719970a33e3e5beb4ad84832dad91bd9fe8de1f6cb1c6a7cb6e90c3bc10a20c67@18.199.185.236:30303?discport=30303,enode://a3317a4ec26ad3cedddb1951105699757fc74ed35c7bc6e31a6fe08b383fad3540ccf7c2f6d617411c74a22cf81a8a3898cf845c7a1501a969229c6ee046042f@52.28.153.174:30303?discport=30303
      - --nat=extip:${EXTERNAL_IP}
    ports:
      - "30303:30303"
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "6060:6060"
    volumes:
      - ./data:/data
      - ./jwt:/jwt
      - ./network-configs:/network-configs
    restart: unless-stopped

  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse-node
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/data/lighthouse/beacon-data
      - --disable-enr-auto-update
      - --enr-address=${EXTERNAL_IP}
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --listen-address=0.0.0.0
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --always-prepare-payload
      - --prepare-payload-lookahead=12000
      - --slots-per-restore-point=32
      - --disable-packet-filter
      - --checkpoint-sync-url=https://bn.bootnode.helder-devnets.xyz/
      - --execution-endpoints=http://geth:8551
      - --suggested-fee-recipient=${COINBASE_ADDRESS}
      - --subscribe-all-subnets
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --enable-private-discovery
      - --testnet-dir=/network-configs
      - --jwt-secrets=/jwt/jwtsecret
      - --boot-nodes=-Iq4QK3EWjpB_Wh4Nh9qDWsIlkwCo-ltVJIOZintRmXlq4BqSO3MgChdjo5bNSc_dBVcnhM_CZidGE-CMjazCeJhn7OGAZA6aA31gmlkgnY0gmlwhDQ6SFGJc2VjcDI1NmsxoQN4MIj6Xe7PBxpfvrpyDe2OkrcIq0gdj38hHXpWjB6Zl4N1ZHCCIyk,enr:-LK4QJIhICEs-MIlzVGEOJRco5B3eR1HjsoPrnlNdCifHlT_NQCaY51Z-ntBIgUQmNRcEBqBogOhh43BYdMR_d9Z-DgKh2F0dG5ldHOIAAYAAAAAAACEZXRoMpBLd1oGYBMnNj9CDwAAAAAAgmlkgnY0gmlwhDQ6SFGJc2VjcDI1NmsxoQOy0WhSLuSWpKXex_SG9dn4bOk-LURo7ZjaUuQ1Fbdbk4N0Y3CCIyiDdWRwgiMo,enr:-MS4QKp7W7f8BsoB04SovlJFZDhs67ZgFK_h5TwBXItLoJfGMPDCLnReASmmig_7kxCNf08e68FrCVM3FcPV0ttR92sWh2F0dG5ldHOIAAAwAAAAAACEZXRoMpBLd1oGYBMnNj9CDwAAAAAAgmlkgnY0gmlwhBLAKEyEcXVpY4IjKYlzZWNwMjU2azGhAxUCn447F0j2DEeA-PqFdp5GP3VpXRWgia2yKjeT62G2iHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo,enr:-MS4QAvcfEmj00GqJcvkjcvQIhBi6pJQ9Znnp2Hr_Hh4YEOzWMENkleVt-vGAAgz8bhFedR5JkcfuzHTzY-9EpB43n4Ph2F0dG5ldHOIAAAAAAAAAMCEZXRoMpBLd1oGYBMnNj9CDwAAAAAAgmlkgnY0gmlwhCOcsdeEcXVpY4IjKYlzZWNwMjU2azGhAo8AZqqrsuBrbMLHdavhLdAxLWpcSk-SPDuqjJt5Fe_oiHN5bmNuZXRzD4N0Y3CCIyiDdWRwgiMo,enr:-MS4QDvmIhX8vI8_kK62XXbO9gnrm-YuzXKo-OS07uRKLgijLfxeUPvtKU-Ps2RnxOEoNq9RPqhbeVdAVYO71eAJvRkPh2F0dG5ldHOIAAAAAAAAABiEZXRoMpBLd1oGYBMnNj9CDwAAAAAAgmlkgnY0gmlwhBLHueyEcXVpY4IjKYlzZWNwMjU2azGhA4ZmLIctckMGhbOwtpgUI2RNeH2S7LXmwpX_onBAfW_AiHN5bmNuZXRzD4N0Y3CCIyiDdWRwgiMo,enr:-MS4QGcM6eqjhCp_Ag7gMzkU8ks7F-S2QsoIdeEsbcB8TPefYK19ymkwmTcpmZfbTJRMwwAvqdOMmGWEAI5GYv_7xZwTh2F0dG5ldHOIAAAAAAAMAACEZXRoMpBLd1oGYBMnNj9CDwAAAAAAgmlkgnY0gmlwhDQcma6EcXVpY4IjKYlzZWNwMjU2azGhAnXOGXUDHbcgGJeZ9-ftr8cihtkyfUfNlpQNe9G8P2PCiHN5bmNuZXRzD4N0Y3CCIyiDdWRwgiMo
      - --builder=http://188.245.207.191:9062
      - --builder-fallback-disable-checks
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "4000:4000"
      - "5054:5054"
    volumes:
      - ./data/lighthouse:/data/lighthouse
      - ./network-configs:/network-configs
      - ./jwt:/jwt
    restart: unless-stopped
    depends_on:
      - geth

  validator:
    image: sigp/lighthouse:latest
    container_name: lighthouse-validator
    command:
      - lighthouse
      - validator_client
      - --debug-level=info
      - --datadir=/data/lighthouse/validator-data
      - --http
      - --http-address=0.0.0.0
      - --http-port=5062
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-port=5064
      - --metrics-allow-origin=*
      - --beacon-nodes=http://lighthouse-node:4000
      - --suggested-fee-recipient=${COINBASE_ADDRESS}
      - --testnet-dir=/network-configs
      - --init-slashing-protection
      - --unencrypted-http-transport
      - --builder-proposals
      - --prefer-builder-proposals
    volumes:
      - ./validator:/data/lighthouse
      - ./network-configs:/network-configs
      - ./keytores:/data/lighthouse/validator-data/validators/keytores
    ports:
      - "5062:5062"
      - "5064:5064"
    depends_on:
      - lighthouse
    restart: unless-stopped


# init geth 
# docker compose run --rm geth init --datadir=/data/geth/execution-data --state.scheme=hash /network-configs/genesis.json

# docker compose run --rm validator lighthouse account validator import --datadir=/data/lighthouse/validator-data --testnet-dir=/network-configs --directory=/data/lighthouse/validator